
CFLAGS = -O2 -Wall -DDEBUG
#CFLAGS = -O2

TARGET=rserver.o rserver rcopy.o rcopy


all: $(TARGET)

.c.o: functions.h functions.c
	$(CC) -c $(CFLAGS) $<

rserver: rserver.c functions.o
	$(CC) -o rserver rserver.o functions.o

rcopy: rcopy.o functions.o
	$(CC) -o rcopy rcopy.o functions.o

indent:
	indent -kr -ts4 *.c

clean:
	$(RM) $(TARGET) *.o *~

